repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
    -   id: check-added-large-files
    -   id: check-case-conflict
    -   id: detect-private-key
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    -   id: check-merge-conflict
-   repo: https://github.com/codespell-project/codespell
    rev: 'v2.2.1'
    hooks:
    -   id: codespell
        args: ["-I", "codespell.txt"]
- repo: https://github.com/jonasbb/pre-commit-latex-hooks
  rev: v1.3.0
  hooks:
  - id: american-eg-ie
  - id: cleveref-capitalization
  - id: csquotes
  - id: no-space-in-cite

exclude: '.*\.sty|.*\.bst|.*\.cls|codespell.txt'

ci:
    autoupdate_schedule: monthly
